# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: def574ea0a909ebf7d453c4f67e1111a5d84071a53e148672f7319954c6c7df657ac3195a30f108b67d18cbbe1cf3e8d2801eeadbf78241399af691f35d175c4

test:
  secret_key_base: 65e34ec4097e3dc325c68d80a78721686a533d3877733d841eabfd9ffd91bb9cefd096c8464976f103ad3fc49f3c64520c989b7eec8a25023f071ac32f0b4281

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
